In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('inspect_churn.csv')

In [3]:
data

,customer_id,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,Churn
0,932aff1e-186f-418c-8716-28bba167c384,NY,86,area_code_510,False,False,0,70.7,125,12.02,...,17.94,174.6,107,7.86,0.0,0,0.00,2,False,0
1,143a0b05-b95a-4d00-ad2a-9c1b18234c29,VT,165,area_code_510,False,False,0,242.9,126,41.29,...,17.83,228.4,126,10.28,0.0,0,0.00,1,False,0
2,45debf35-7e4d-42da-ba4e-d737a8997e16,KS,70,area_code_415,False,False,0,222.8,114,37.88,...,18.35,223.5,122,10.06,0.0,0,0.00,1,False,0
3,76b4b68f-1113-4411-88ad-de38b482e9fb,NM,158,area_code_408,False,False,0,172.4,114,29.31,...,21.81,235.3,104,10.59,0.0,0,0.00,2,False,0
4,6ee9cecd-1a09-4f4a-937e-aa848c392bed,ND,101,area_code_415,False,False,0,217.7,118,37.01,...,19.69,185.3,128,8.34,0.0,0,0.00,3,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,e1db5067-6484-4a5d-b68d-ab869fff027d,UT,36,area_code_415,False,True,16,149.4,111,25.40,...,11.20,132.7,87,5.97,6.7,2,1.81,0,False,0
4246,99ad8c1e-c90b-44d5-ad36-d4d87aae0d85,MN,24,area_code_510,False,True,25,164.9,110,28.03,...,17.79,231.2,55,10.40,6.7,9,1.81,1,False,0
4247,b2287275-f563-40ae-ad9c-06844ca539f4,DE,97,area_code_415,False,True,32,183.4,94,31.18,...,22.87,203.5,38,9.16,6.7,4,1.81,5,False,0
4248,9908263a-a9c9-48f5-9c26-ca7cc9bd5917,IN,81,area_code_408,False,True,46,168.3,124,28.61,...,23.03,222.5,98,10.01,6.7,2,1.81,4,False,0
4249,ab236f86-ad9b-461e-9193-3176d3925a1f,VA,133,area_code_408,False,True,39,239.9,107,40.78,...,21.57,128.7,85,5.79,6.7,3,1.81,5,False,0

In [4]:
data = data.drop_duplicates()

print("Remaining duplicates:", data.duplicated().sum())

Remaining duplicates: 0

In [6]:
print(data["Churn"].unique())

[0 1]

In [7]:
for col in data.columns:
    if data[col].dtype == "object":
        try:
            data[col] = pd.to_numeric(data[col])
        except:
            pass

In [10]:
data

,customer_id,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,Churn
0,932aff1e-186f-418c-8716-28bba167c384,NY,86,area_code_510,False,False,0,70.7,125,12.02,...,17.94,174.6,107,7.86,0.0,0,0.00,2,False,0
1,143a0b05-b95a-4d00-ad2a-9c1b18234c29,VT,165,area_code_510,False,False,0,242.9,126,41.29,...,17.83,228.4,126,10.28,0.0,0,0.00,1,False,0
2,45debf35-7e4d-42da-ba4e-d737a8997e16,KS,70,area_code_415,False,False,0,222.8,114,37.88,...,18.35,223.5,122,10.06,0.0,0,0.00,1,False,0
3,76b4b68f-1113-4411-88ad-de38b482e9fb,NM,158,area_code_408,False,False,0,172.4,114,29.31,...,21.81,235.3,104,10.59,0.0,0,0.00,2,False,0
4,6ee9cecd-1a09-4f4a-937e-aa848c392bed,ND,101,area_code_415,False,False,0,217.7,118,37.01,...,19.69,185.3,128,8.34,0.0,0,0.00,3,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,e1db5067-6484-4a5d-b68d-ab869fff027d,UT,36,area_code_415,False,True,16,149.4,111,25.40,...,11.20,132.7,87,5.97,6.7,2,1.81,0,False,0
4246,99ad8c1e-c90b-44d5-ad36-d4d87aae0d85,MN,24,area_code_510,False,True,25,164.9,110,28.03,...,17.79,231.2,55,10.40,6.7,9,1.81,1,False,0
4247,b2287275-f563-40ae-ad9c-06844ca539f4,DE,97,area_code_415,False,True,32,183.4,94,31.18,...,22.87,203.5,38,9.16,6.7,4,1.81,5,False,0
4248,9908263a-a9c9-48f5-9c26-ca7cc9bd5917,IN,81,area_code_408,False,True,46,168.3,124,28.61,...,23.03,222.5,98,10.01,6.7,2,1.81,4,False,0
4249,ab236f86-ad9b-461e-9193-3176d3925a1f,VA,133,area_code_408,False,True,39,239.9,107,40.78,...,21.57,128.7,85,5.79,6.7,3,1.81,5,False,0

In [ ]:
# data = data.drop(columns=["unnecessary_column_name"])