In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("C:/Users/ashuy/OneDrive/Desktop/FINAL YEAR PROJECT/code/Intelligent-Customer-Churn-Prediction-System/cleaned_dataset.csv")

In [4]:
#Create tenure groups (using account_length)
df['tenure_group'] = pd.cut(df['account_length'],
                            bins=[0,50,100,150,200,300],
                            labels=['0-50','50-100','100-150','150-200','200+'])

In [5]:
#Create average revenue per month
df['avg_revenue_per_month'] = (
    df['total_day_charge'] +
    df['total_eve_charge'] +
    df['total_night_charge'] +
    df['total_intl_charge']
)

In [6]:
#Create total spending feature
df['total_spending'] = (
    df['total_day_charge'] +
    df['total_eve_charge'] +
    df['total_night_charge'] +
    df['total_intl_charge']
) * df['account_length']

In [7]:
#Convert categorical columns
#label encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['international_plan'] = le.fit_transform(df['international_plan'])
df['voice_mail_plan'] = le.fit_transform(df['voice_mail_plan'])

In [8]:
#One-Hot Encoding
df = pd.get_dummies(df, columns=['state','tenure_group'], drop_first=True)

In [10]:
#Scale numeric features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numeric_cols = df.select_dtypes(include=['int64','float64']).columns

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [11]:
#Check imbalance ratio
df['Churn'].value_counts()

Churn
-0.404655    3652
 2.471239     598
Name: count, dtype: int64

In [15]:
df = df.drop(columns=['customer_id'])

In [16]:
#Convert categorical columns to numeric
df['international_plan'] = df['international_plan'].map({'yes':1, 'no':0})
df['voice_mail_plan'] = df['voice_mail_plan'].map({'yes':1, 'no':0})

In [18]:
df.columns

Index(['account_length', 'area_code', 'international_plan', 'voice_mail_plan',
       'number_vmail_messages', 'total_day_minutes', 'total_day_calls',
       'total_day_charge', 'total_eve_minutes', 'total_eve_calls',
       'total_eve_charge', 'total_night_minutes', 'total_night_calls',
       'total_night_charge', 'total_intl_minutes', 'total_intl_calls',
       'total_intl_charge', 'number_customer_service_calls', 'churn', 'Churn',
       'avg_revenue_per_month', 'total_spending', 'state_AL', 'state_AR',
       'state_AZ', 'state_CA', 'state_CO', 'state_CT', 'state_DC', 'state_DE',
       'state_FL', 'state_GA', 'state_HI', 'state_IA', 'state_ID', 'state_IL',
       'state_IN', 'state_KS', 'state_KY', 'state_LA', 'state_MA', 'state_MD',
       'state_ME', 'state_MI', 'state_MN', 'state_MO', 'state_MS', 'state_MT',
       'state_NC', 'state_ND', 'state_NE', 'state_NH', 'state_NJ', 'state_NM',
       'state_NV', 'state_NY', 'state_OH', 'state_OK', 'state_OR', 'state_PA',
       'state_RI', 'state_SC', 'state_SD', 'state_TN', 'state_TX', 'state_UT',
       'state_VA', 'state_VT', 'state_WA', 'state_WI', 'state_WV', 'state_WY',
       'tenure_group_50-100', 'tenure_group_100-150', 'tenure_group_150-200',
       'tenure_group_200+'],
      dtype='object')

In [19]:
df.head()

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,...,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY,tenure_group_50-100,tenure_group_100-150,tenure_group_150-200,tenure_group_200+
0,-0.358652,area_code_510,NaN,NaN,-0.567911,-2.028655,1.264213,-2.028608,0.215472,0.644196,...,False,False,False,False,False,False,True,False,False,False
1,1.631587,area_code_510,NaN,NaN,-0.567911,1.159878,1.314595,1.159492,0.191588,-1.767107,...,False,True,False,False,False,False,False,False,True,False
2,-0.761738,area_code_415,NaN,NaN,-0.567911,0.787697,0.710014,0.788074,0.312997,0.644196,...,False,False,False,False,False,False,True,False,False,False
3,1.455237,area_code_408,NaN,NaN,-0.567911,-0.145532,0.710014,-0.145374,1.123050,-1.566165,...,False,False,False,False,False,False,False,False,True,False
4,0.019241,area_code_415,NaN,NaN,-0.567911,0.693263,0.911541,0.693313,0.627465,1.397728,...,False,False,False,False,False,False,False,True,False,False

In [20]:
df = df.drop(columns=['churn'])

In [21]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [23]:
df.dtypes

account_length           float64
area_code                 object
international_plan       float64
voice_mail_plan          float64
number_vmail_messages    float64
                          ...
state_WY                    bool
tenure_group_50-100         bool
tenure_group_100-150        bool
tenure_group_150-200        bool
tenure_group_200+           bool
Length: 75, dtype: object

In [27]:

df.to_csv("final_features.csv", index=False)

In [28]:
df

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,...,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY,tenure_group_50-100,tenure_group_100-150,tenure_group_150-200,tenure_group_200+
0,-0.358652,area_code_510,NaN,NaN,-0.567911,-2.028655,1.264213,-2.028608,0.215472,0.644196,...,False,False,False,False,False,False,True,False,False,False
1,1.631587,area_code_510,NaN,NaN,-0.567911,1.159878,1.314595,1.159492,0.191588,-1.767107,...,False,True,False,False,False,False,False,False,True,False
2,-0.761738,area_code_415,NaN,NaN,-0.567911,0.787697,0.710014,0.788074,0.312997,0.644196,...,False,False,False,False,False,False,True,False,False,False
3,1.455237,area_code_408,NaN,NaN,-0.567911,-0.145532,0.710014,-0.145374,1.123050,-1.566165,...,False,False,False,False,False,False,False,False,True,False
4,0.019241,area_code_415,NaN,NaN,-0.567911,0.693263,0.911541,0.693313,0.627465,1.397728,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,-1.618297,area_code_415,NaN,NaN,0.622715,-0.571410,0.558869,-0.571253,-1.360848,0.644196,...,False,False,False,False,False,False,False,False,False,False
4246,-1.920612,area_code_510,NaN,NaN,1.292443,-0.284405,0.508488,-0.284792,0.181637,0.242312,...,False,False,False,False,False,False,False,False,False,False
4247,-0.081530,area_code_415,NaN,NaN,1.813342,0.058149,-0.297619,0.058307,1.371838,0.995845,...,False,False,False,False,False,False,True,False,False,False
4248,-0.484616,area_code_408,NaN,NaN,2.855140,-0.221449,1.213831,-0.221618,1.407664,0.141841,...,False,False,False,False,False,False,True,False,False,False
4249,0.825414,area_code_408,NaN,NaN,2.334241,1.104329,0.357342,1.103943,1.067322,-1.164281,...,True,False,False,False,False,False,False,True,False,False