In [1]:
import pandas as pd
data=pd.read_csv("C:/Users/ashuy/OneDrive/Desktop/FINAL YEAR PROJECT/archive/churn.csv")

In [2]:
data

,customer_id,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,932aff1e-186f-418c-8716-28bba167c384,NY,86,area_code_510,False,False,0,70.7,125,12.02,...,113,17.94,174.6,107,7.86,0.0,0,0.00,2,False
1,143a0b05-b95a-4d00-ad2a-9c1b18234c29,VT,165,area_code_510,False,False,0,242.9,126,41.29,...,65,17.83,228.4,126,10.28,0.0,0,0.00,1,False
2,45debf35-7e4d-42da-ba4e-d737a8997e16,KS,70,area_code_415,False,False,0,222.8,114,37.88,...,113,18.35,223.5,122,10.06,0.0,0,0.00,1,False
3,76b4b68f-1113-4411-88ad-de38b482e9fb,NM,158,area_code_408,False,False,0,172.4,114,29.31,...,69,21.81,235.3,104,10.59,0.0,0,0.00,2,False
4,6ee9cecd-1a09-4f4a-937e-aa848c392bed,ND,101,area_code_415,False,False,0,217.7,118,37.01,...,128,19.69,185.3,128,8.34,0.0,0,0.00,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,e1db5067-6484-4a5d-b68d-ab869fff027d,UT,36,area_code_415,False,True,16,149.4,111,25.40,...,113,11.20,132.7,87,5.97,6.7,2,1.81,0,False
4246,99ad8c1e-c90b-44d5-ad36-d4d87aae0d85,MN,24,area_code_510,False,True,25,164.9,110,28.03,...,105,17.79,231.2,55,10.40,6.7,9,1.81,1,False
4247,b2287275-f563-40ae-ad9c-06844ca539f4,DE,97,area_code_415,False,True,32,183.4,94,31.18,...,120,22.87,203.5,38,9.16,6.7,4,1.81,5,False
4248,9908263a-a9c9-48f5-9c26-ca7cc9bd5917,IN,81,area_code_408,False,True,46,168.3,124,28.61,...,103,23.03,222.5,98,10.01,6.7,2,1.81,4,False
4249,ab236f86-ad9b-461e-9193-3176d3925a1f,VA,133,area_code_408,False,True,39,239.9,107,40.78,...,77,21.57,128.7,85,5.79,6.7,3,1.81,5,False

In [3]:
print(data.columns)

Index(['customer_id', 'state', 'account_length', 'area_code',
       'international_plan', 'voice_mail_plan', 'number_vmail_messages',
       'total_day_minutes', 'total_day_calls', 'total_day_charge',
       'total_eve_minutes', 'total_eve_calls', 'total_eve_charge',
       'total_night_minutes', 'total_night_calls', 'total_night_charge',
       'total_intl_minutes', 'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'churn'],
      dtype='object')

In [4]:
data.dtypes

customer_id                       object
state                             object
account_length                     int64
area_code                         object
international_plan                  bool
voice_mail_plan                     bool
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                               bool
dtype: object

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4250 entries, 0 to 4249
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    4250 non-null   object
 1   state                          4250 non-null   object
 2   account_length                 4250 non-null   int64
 3   area_code                      4250 non-null   object
 4   international_plan             4250 non-null   bool
 5   voice_mail_plan                4250 non-null   bool
 6   number_vmail_messages          4250 non-null   int64
 7   total_day_minutes              4250 non-null   float64
 8   total_day_calls                4250 non-null   int64
 9   total_day_charge               4250 non-null   float64
 10  total_eve_minutes              4250 non-null   float64
 11  total_eve_calls                4250 non-null   int64
 12  total_eve_charge               4250 non-null   float64
 13  total_night_minutes            4250 non-null   float64
 14  total_night_calls              4250 non-null   int64
 15  total_night_charge             4250 non-null   float64
 16  total_intl_minutes             4250 non-null   float64
 17  total_intl_calls               4250 non-null   int64
 18  total_intl_charge              4250 non-null   float64
 19  number_customer_service_calls  4250 non-null   int64
 20  churn                          4250 non-null   bool
dtypes: bool(3), float64(8), int64(7), object(3)
memory usage: 610.2+ KB

In [6]:
data.shape

(4250, 21)

In [7]:
data.columns

Index(['customer_id', 'state', 'account_length', 'area_code',
       'international_plan', 'voice_mail_plan', 'number_vmail_messages',
       'total_day_minutes', 'total_day_calls', 'total_day_charge',
       'total_eve_minutes', 'total_eve_calls', 'total_eve_charge',
       'total_night_minutes', 'total_night_calls', 'total_night_charge',
       'total_intl_minutes', 'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'churn'],
      dtype='object')

In [8]:
data.isnull().sum()

customer_id                      0
state                            0
account_length                   0
area_code                        0
international_plan               0
voice_mail_plan                  0
number_vmail_messages            0
total_day_minutes                0
total_day_calls                  0
total_day_charge                 0
total_eve_minutes                0
total_eve_calls                  0
total_eve_charge                 0
total_night_minutes              0
total_night_calls                0
total_night_charge               0
total_intl_minutes               0
total_intl_calls                 0
total_intl_charge                0
number_customer_service_calls    0
churn                            0
dtype: int64

In [9]:
(data.isnull().sum() / len(data)) * 100

customer_id                      0.0
state                            0.0
account_length                   0.0
area_code                        0.0
international_plan               0.0
voice_mail_plan                  0.0
number_vmail_messages            0.0
total_day_minutes                0.0
total_day_calls                  0.0
total_day_charge                 0.0
total_eve_minutes                0.0
total_eve_calls                  0.0
total_eve_charge                 0.0
total_night_minutes              0.0
total_night_calls                0.0
total_night_charge               0.0
total_intl_minutes               0.0
total_intl_calls                 0.0
total_intl_charge                0.0
number_customer_service_calls    0.0
churn                            0.0
dtype: float64

In [10]:
data.duplicated().sum()

np.int64(0)

In [11]:
# Select categorical columns
categorical_cols = data.select_dtypes(include=['object']).columns

for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(data[col].unique())

Column: customer_id
['932aff1e-186f-418c-8716-28bba167c384'
 '143a0b05-b95a-4d00-ad2a-9c1b18234c29'
 '45debf35-7e4d-42da-ba4e-d737a8997e16' ...
 'b2287275-f563-40ae-ad9c-06844ca539f4'
 '9908263a-a9c9-48f5-9c26-ca7cc9bd5917'
 'ab236f86-ad9b-461e-9193-3176d3925a1f']

Column: state
['NY' 'VT' 'KS' 'NM' 'ND' 'OH' 'SC' 'MN' 'VA' 'MS' 'MA' 'FL' 'CA' 'WI'
 'MO' 'AL' 'NE' 'WA' 'NJ' 'IN' 'DE' 'NH' 'ID' 'WV' 'CT' 'CO' 'HI' 'IA'
 'MT' 'RI' 'KY' 'AR' 'NC' 'AK' 'SD' 'PA' 'UT' 'MI' 'WY' 'NV' 'OK' 'GA'
 'MD' 'OR' 'DC' 'IL' 'LA' 'TN' 'TX' 'ME' 'AZ']

Column: area_code
['area_code_510' 'area_code_415' 'area_code_408']

In [12]:
for col in categorical_cols:
    print(f"\nValue counts for {col}")
    print(data[col].value_counts())

Value counts for customer_id
customer_id
ab236f86-ad9b-461e-9193-3176d3925a1f    1
932aff1e-186f-418c-8716-28bba167c384    1
143a0b05-b95a-4d00-ad2a-9c1b18234c29    1
45debf35-7e4d-42da-ba4e-d737a8997e16    1
76b4b68f-1113-4411-88ad-de38b482e9fb    1
                                       ..
c93537ea-9eb4-4627-b1f6-2d704ec4da3c    1
5c343cdc-df1a-435e-b006-e4a53d34858c    1
199827e2-af95-4856-acc3-5bd7d96f02e9    1
87e21d3a-5445-4891-bdac-21a32afd1186    1
fbbd3ce1-b4ee-4459-b4eb-576a65b06cc1    1
Name: count, Length: 4250, dtype: int64

Value counts for state
state
WV    139
MN    108
ID    106
AL    101
VA    100
OR     99
TX     98
UT     97
NY     96
NJ     96
OH     95
WY     95
WI     94
MA     89
ME     89
CT     88
KS     87
RI     87
MI     87
MD     86
VT     86
KY     85
NV     83
IN     83
MS     82
MO     80
WA     80
NC     80
MT     80
CO     80
DE     80
TN     79
IL     79
OK     78
NM     78
NH     78
HI     77
AZ     77
FL     76
SD     75
NE     73
SC     72
DC     72
AR     71
LA     69
PA     67
ND     67
GA     64
IA     62
AK     61
CA     39
Name: count, dtype: int64

Value counts for area_code
area_code
area_code_415    2108
area_code_408    1086
area_code_510    1056
Name: count, dtype: int64

In [13]:
# Example: CustomerID column
data["customer_id"].nunique()

4250

In [14]:
data.shape

(4250, 21)

In [15]:
data["churn"].unique()

array([False,  True])

In [16]:
# data["Churn"] = data["churn"].map({"True": 1, "False": 0})

In [17]:
# data["Churn"].isnull().sum()

In [18]:
# data["Churn"].unique()

In [19]:
data

,customer_id,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,932aff1e-186f-418c-8716-28bba167c384,NY,86,area_code_510,False,False,0,70.7,125,12.02,...,113,17.94,174.6,107,7.86,0.0,0,0.00,2,False
1,143a0b05-b95a-4d00-ad2a-9c1b18234c29,VT,165,area_code_510,False,False,0,242.9,126,41.29,...,65,17.83,228.4,126,10.28,0.0,0,0.00,1,False
2,45debf35-7e4d-42da-ba4e-d737a8997e16,KS,70,area_code_415,False,False,0,222.8,114,37.88,...,113,18.35,223.5,122,10.06,0.0,0,0.00,1,False
3,76b4b68f-1113-4411-88ad-de38b482e9fb,NM,158,area_code_408,False,False,0,172.4,114,29.31,...,69,21.81,235.3,104,10.59,0.0,0,0.00,2,False
4,6ee9cecd-1a09-4f4a-937e-aa848c392bed,ND,101,area_code_415,False,False,0,217.7,118,37.01,...,128,19.69,185.3,128,8.34,0.0,0,0.00,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,e1db5067-6484-4a5d-b68d-ab869fff027d,UT,36,area_code_415,False,True,16,149.4,111,25.40,...,113,11.20,132.7,87,5.97,6.7,2,1.81,0,False
4246,99ad8c1e-c90b-44d5-ad36-d4d87aae0d85,MN,24,area_code_510,False,True,25,164.9,110,28.03,...,105,17.79,231.2,55,10.40,6.7,9,1.81,1,False
4247,b2287275-f563-40ae-ad9c-06844ca539f4,DE,97,area_code_415,False,True,32,183.4,94,31.18,...,120,22.87,203.5,38,9.16,6.7,4,1.81,5,False
4248,9908263a-a9c9-48f5-9c26-ca7cc9bd5917,IN,81,area_code_408,False,True,46,168.3,124,28.61,...,103,23.03,222.5,98,10.01,6.7,2,1.81,4,False
4249,ab236f86-ad9b-461e-9193-3176d3925a1f,VA,133,area_code_408,False,True,39,239.9,107,40.78,...,77,21.57,128.7,85,5.79,6.7,3,1.81,5,False

In [27]:
data["Churn"] = data["churn"].replace({True: 1, False: 0})
data["Churn"] = data["churn"].astype("Int64")

C:\Users\ashuy\AppData\Local\Temp\ipykernel_14552\4117661971.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Churn"] = data["churn"].replace({True: 1, False: 0})

In [28]:
data

,customer_id,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,Churn
0,932aff1e-186f-418c-8716-28bba167c384,NY,86,area_code_510,False,False,0,70.7,125,12.02,...,17.94,174.6,107,7.86,0.0,0,0.00,2,False,0
1,143a0b05-b95a-4d00-ad2a-9c1b18234c29,VT,165,area_code_510,False,False,0,242.9,126,41.29,...,17.83,228.4,126,10.28,0.0,0,0.00,1,False,0
2,45debf35-7e4d-42da-ba4e-d737a8997e16,KS,70,area_code_415,False,False,0,222.8,114,37.88,...,18.35,223.5,122,10.06,0.0,0,0.00,1,False,0
3,76b4b68f-1113-4411-88ad-de38b482e9fb,NM,158,area_code_408,False,False,0,172.4,114,29.31,...,21.81,235.3,104,10.59,0.0,0,0.00,2,False,0
4,6ee9cecd-1a09-4f4a-937e-aa848c392bed,ND,101,area_code_415,False,False,0,217.7,118,37.01,...,19.69,185.3,128,8.34,0.0,0,0.00,3,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,e1db5067-6484-4a5d-b68d-ab869fff027d,UT,36,area_code_415,False,True,16,149.4,111,25.40,...,11.20,132.7,87,5.97,6.7,2,1.81,0,False,0
4246,99ad8c1e-c90b-44d5-ad36-d4d87aae0d85,MN,24,area_code_510,False,True,25,164.9,110,28.03,...,17.79,231.2,55,10.40,6.7,9,1.81,1,False,0
4247,b2287275-f563-40ae-ad9c-06844ca539f4,DE,97,area_code_415,False,True,32,183.4,94,31.18,...,22.87,203.5,38,9.16,6.7,4,1.81,5,False,0
4248,9908263a-a9c9-48f5-9c26-ca7cc9bd5917,IN,81,area_code_408,False,True,46,168.3,124,28.61,...,23.03,222.5,98,10.01,6.7,2,1.81,4,False,0
4249,ab236f86-ad9b-461e-9193-3176d3925a1f,VA,133,area_code_408,False,True,39,239.9,107,40.78,...,21.57,128.7,85,5.79,6.7,3,1.81,5,False,0

In [29]:
data["Churn"].unique()

<IntegerArray>
[0, 1]
Length: 2, dtype: Int64

In [30]:
print("Shape:", data.shape)
print("\nColumns:", data.columns)
print("\nData Types:\n", data.dtypes)
print("\nMissing Values:\n", data.isnull().sum())
print("\nDuplicate Rows:", data.duplicated().sum())
print("\nChurn Values:", data["Churn"].unique())

Shape: (4250, 22)

Columns: Index(['customer_id', 'state', 'account_length', 'area_code',
       'international_plan', 'voice_mail_plan', 'number_vmail_messages',
       'total_day_minutes', 'total_day_calls', 'total_day_charge',
       'total_eve_minutes', 'total_eve_calls', 'total_eve_charge',
       'total_night_minutes', 'total_night_calls', 'total_night_charge',
       'total_intl_minutes', 'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'churn', 'Churn'],
      dtype='object')

Data Types:
 customer_id                       object
state                             object
account_length                     int64
area_code                         object
international_plan                  bool
voice_mail_plan                     bool
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                               bool
Churn                              Int64
dtype: object

Missing Values:
 customer_id                      0
state                            0
account_length                   0
area_code                        0
international_plan               0
voice_mail_plan                  0
number_vmail_messages            0
total_day_minutes                0
total_day_calls                  0
total_day_charge                 0
total_eve_minutes                0
total_eve_calls                  0
total_eve_charge                 0
total_night_minutes              0
total_night_calls                0
total_night_charge               0
total_intl_minutes               0
total_intl_calls                 0
total_intl_charge                0
number_customer_service_calls    0
churn                            0
Churn                            0
dtype: int64

Duplicate Rows: 0

Churn Values: <IntegerArray>
[0, 1]
Length: 2, dtype: Int64

In [31]:
data

,customer_id,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,...,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,Churn
0,932aff1e-186f-418c-8716-28bba167c384,NY,86,area_code_510,False,False,0,70.7,125,12.02,...,17.94,174.6,107,7.86,0.0,0,0.00,2,False,0
1,143a0b05-b95a-4d00-ad2a-9c1b18234c29,VT,165,area_code_510,False,False,0,242.9,126,41.29,...,17.83,228.4,126,10.28,0.0,0,0.00,1,False,0
2,45debf35-7e4d-42da-ba4e-d737a8997e16,KS,70,area_code_415,False,False,0,222.8,114,37.88,...,18.35,223.5,122,10.06,0.0,0,0.00,1,False,0
3,76b4b68f-1113-4411-88ad-de38b482e9fb,NM,158,area_code_408,False,False,0,172.4,114,29.31,...,21.81,235.3,104,10.59,0.0,0,0.00,2,False,0
4,6ee9cecd-1a09-4f4a-937e-aa848c392bed,ND,101,area_code_415,False,False,0,217.7,118,37.01,...,19.69,185.3,128,8.34,0.0,0,0.00,3,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,e1db5067-6484-4a5d-b68d-ab869fff027d,UT,36,area_code_415,False,True,16,149.4,111,25.40,...,11.20,132.7,87,5.97,6.7,2,1.81,0,False,0
4246,99ad8c1e-c90b-44d5-ad36-d4d87aae0d85,MN,24,area_code_510,False,True,25,164.9,110,28.03,...,17.79,231.2,55,10.40,6.7,9,1.81,1,False,0
4247,b2287275-f563-40ae-ad9c-06844ca539f4,DE,97,area_code_415,False,True,32,183.4,94,31.18,...,22.87,203.5,38,9.16,6.7,4,1.81,5,False,0
4248,9908263a-a9c9-48f5-9c26-ca7cc9bd5917,IN,81,area_code_408,False,True,46,168.3,124,28.61,...,23.03,222.5,98,10.01,6.7,2,1.81,4,False,0
4249,ab236f86-ad9b-461e-9193-3176d3925a1f,VA,133,area_code_408,False,True,39,239.9,107,40.78,...,21.57,128.7,85,5.79,6.7,3,1.81,5,False,0

In [32]:
data.to_csv('inspect_churn.csv', index=False)