In [1]:
import pandas as pd
df=pd.read_csv("C:/Users/ashuy/OneDrive/Desktop/FINAL YEAR PROJECT/code/Intelligent-Customer-Churn-Prediction-System/final_features.csv")

In [2]:
df

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,...,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY,tenure_group_50-100,tenure_group_100-150,tenure_group_150-200,tenure_group_200+
0,-0.358652,area_code_510,NaN,NaN,-0.567911,-2.028655,1.264213,-2.028608,0.215472,0.644196,...,False,False,False,False,False,False,True,False,False,False
1,1.631587,area_code_510,NaN,NaN,-0.567911,1.159878,1.314595,1.159492,0.191588,-1.767107,...,False,True,False,False,False,False,False,False,True,False
2,-0.761738,area_code_415,NaN,NaN,-0.567911,0.787697,0.710014,0.788074,0.312997,0.644196,...,False,False,False,False,False,False,True,False,False,False
3,1.455237,area_code_408,NaN,NaN,-0.567911,-0.145532,0.710014,-0.145374,1.123050,-1.566165,...,False,False,False,False,False,False,False,False,True,False
4,0.019241,area_code_415,NaN,NaN,-0.567911,0.693263,0.911541,0.693313,0.627465,1.397728,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,-1.618297,area_code_415,NaN,NaN,0.622715,-0.571410,0.558869,-0.571253,-1.360848,0.644196,...,False,False,False,False,False,False,False,False,False,False
4246,-1.920612,area_code_510,NaN,NaN,1.292443,-0.284405,0.508488,-0.284792,0.181637,0.242312,...,False,False,False,False,False,False,False,False,False,False
4247,-0.081530,area_code_415,NaN,NaN,1.813342,0.058149,-0.297619,0.058307,1.371838,0.995845,...,False,False,False,False,False,False,True,False,False,False
4248,-0.484616,area_code_408,NaN,NaN,2.855140,-0.221449,1.213831,-0.221618,1.407664,0.141841,...,False,False,False,False,False,False,True,False,False,False
4249,0.825414,area_code_408,NaN,NaN,2.334241,1.104329,0.357342,1.103943,1.067322,-1.164281,...,True,False,False,False,False,False,False,True,False,False

In [3]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [8]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [4]:
# Fill NaNs with 'No' if your columns are Yes/No
df['international_plan'] = df['international_plan'].fillna('No')
df['voice_mail_plan'] = df['voice_mail_plan'].fillna('No')

# If your columns are 1/0, you can fill with 0 instead:
# df['international_plan'] = df['international_plan'].fillna(0)
# df['voice_mail_plan'] = df['voice_mail_plan'].fillna(0)

In [15]:
df

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,...,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY,tenure_group_50-100,tenure_group_100-150,tenure_group_150-200,tenure_group_200+
0,-0.358652,area_code_510,No,No,-0.567911,-2.028655,1.264213,-2.028608,0.215472,0.644196,...,False,False,False,False,False,False,True,False,False,False
1,1.631587,area_code_510,No,No,-0.567911,1.159878,1.314595,1.159492,0.191588,-1.767107,...,False,True,False,False,False,False,False,False,True,False
2,-0.761738,area_code_415,No,No,-0.567911,0.787697,0.710014,0.788074,0.312997,0.644196,...,False,False,False,False,False,False,True,False,False,False
3,1.455237,area_code_408,No,No,-0.567911,-0.145532,0.710014,-0.145374,1.123050,-1.566165,...,False,False,False,False,False,False,False,False,True,False
4,0.019241,area_code_415,No,No,-0.567911,0.693263,0.911541,0.693313,0.627465,1.397728,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,-1.618297,area_code_415,No,No,0.622715,-0.571410,0.558869,-0.571253,-1.360848,0.644196,...,False,False,False,False,False,False,False,False,False,False
4246,-1.920612,area_code_510,No,No,1.292443,-0.284405,0.508488,-0.284792,0.181637,0.242312,...,False,False,False,False,False,False,False,False,False,False
4247,-0.081530,area_code_415,No,No,1.813342,0.058149,-0.297619,0.058307,1.371838,0.995845,...,False,False,False,False,False,False,True,False,False,False
4248,-0.484616,area_code_408,No,No,2.855140,-0.221449,1.213831,-0.221618,1.407664,0.141841,...,False,False,False,False,False,False,True,False,False,False
4249,0.825414,area_code_408,No,No,2.334241,1.104329,0.357342,1.103943,1.067322,-1.164281,...,True,False,False,False,False,False,False,True,False,False

In [6]:
df.to_csv('cleaned_dataset_final.csv', index=False)

In [16]:
import pandas as pd
data=pd.read_csv(")

In [26]:
data

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,...,state_VA,state_VT,state_WA,state_WI,state_WV,state_WY,tenure_group_50-100,tenure_group_100-150,tenure_group_150-200,tenure_group_200+
0,-0.358652,area_code_510,No,No,-0.567911,-2.028655,1.264213,-2.028608,0.215472,0.644196,...,False,False,False,False,False,False,True,False,False,False
1,1.631587,area_code_510,No,No,-0.567911,1.159878,1.314595,1.159492,0.191588,-1.767107,...,False,True,False,False,False,False,False,False,True,False
2,-0.761738,area_code_415,No,No,-0.567911,0.787697,0.710014,0.788074,0.312997,0.644196,...,False,False,False,False,False,False,True,False,False,False
3,1.455237,area_code_408,No,No,-0.567911,-0.145532,0.710014,-0.145374,1.123050,-1.566165,...,False,False,False,False,False,False,False,False,True,False
4,0.019241,area_code_415,No,No,-0.567911,0.693263,0.911541,0.693313,0.627465,1.397728,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,-1.618297,area_code_415,No,No,0.622715,-0.571410,0.558869,-0.571253,-1.360848,0.644196,...,False,False,False,False,False,False,False,False,False,False
4246,-1.920612,area_code_510,No,No,1.292443,-0.284405,0.508488,-0.284792,0.181637,0.242312,...,False,False,False,False,False,False,False,False,False,False
4247,-0.081530,area_code_415,No,No,1.813342,0.058149,-0.297619,0.058307,1.371838,0.995845,...,False,False,False,False,False,False,True,False,False,False
4248,-0.484616,area_code_408,No,No,2.855140,-0.221449,1.213831,-0.221618,1.407664,0.141841,...,False,False,False,False,False,False,True,False,False,False
4249,0.825414,area_code_408,No,No,2.334241,1.104329,0.357342,1.103943,1.067322,-1.164281,...,True,False,False,False,False,False,False,True,False,False

In [18]:
# 6️⃣ Split into features and target
X = df.drop('Churn', axis=1)
y = df['Churn']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit scaler on training data only
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ValueError: could not convert string to float: 'area_code_408'

In [29]:
# Drop the column(s) causing the issue
# df = df.drop(['area_code'], axis=1)
df.to_csv("updated_cleaned_dataset",index=False)

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit scaler on training data only
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ValueError: could not convert string to float: 'area_code_408'

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [23]:
df.columns

Index(['account_length', 'area_code', 'international_plan', 'voice_mail_plan',
       'number_vmail_messages', 'total_day_minutes', 'total_day_calls',
       'total_day_charge', 'total_eve_minutes', 'total_eve_calls',
       'total_eve_charge', 'total_night_minutes', 'total_night_calls',
       'total_night_charge', 'total_intl_minutes', 'total_intl_calls',
       'total_intl_charge', 'number_customer_service_calls', 'Churn',
       'avg_revenue_per_month', 'total_spending', 'state_AL', 'state_AR',
       'state_AZ', 'state_CA', 'state_CO', 'state_CT', 'state_DC', 'state_DE',
       'state_FL', 'state_GA', 'state_HI', 'state_IA', 'state_ID', 'state_IL',
       'state_IN', 'state_KS', 'state_KY', 'state_LA', 'state_MA', 'state_MD',
       'state_ME', 'state_MI', 'state_MN', 'state_MO', 'state_MS', 'state_MT',
       'state_NC', 'state_ND', 'state_NE', 'state_NH', 'state_NJ', 'state_NM',
       'state_NV', 'state_NY', 'state_OH', 'state_OK', 'state_OR', 'state_PA',
       'state_RI', 'state_SC', 'state_SD', 'state_TN', 'state_TX', 'state_UT',
       'state_VA', 'state_VT', 'state_WA', 'state_WI', 'state_WV', 'state_WY',
       'tenure_group_50-100', 'tenure_group_100-150', 'tenure_group_150-200',
       'tenure_group_200+'],
      dtype='object')

In [10]:
X_train = X_train.apply(pd.to_numeric)
X_test = X_test.apply(pd.to_numeric)

NameError: name 'X_train' is not defined

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
model = LogisticRegression()

In [14]:
model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [15]:
nan_counts = df.isna().sum()
print(nan_counts[nan_counts > 0])

international_plan    4250
voice_mail_plan       4250
dtype: int64

In [16]:
# Fill NaNs with 'No' if your columns are Yes/No
df['international_plan'] = df['international_plan'].fillna('No')
df['voice_mail_plan'] = df['voice_mail_plan'].fillna('No')

# If your columns are 1/0, you can fill with 0 instead:
# df['international_plan'] = df['international_plan'].fillna(0)
# df['voice_mail_plan'] = df['voice_mail_plan'].fillna(0)

In [17]:
df

,account_length,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,...,state_WA,state_WI,state_WV,state_WY,tenure_group_50-100,tenure_group_100-150,tenure_group_150-200,tenure_group_200+,area_code_area_code_415,area_code_area_code_510
0,-0.358652,No,No,-0.567911,-2.028655,1.264213,-2.028608,0.215472,0.644196,0.216589,...,False,False,False,False,True,False,False,False,False,True
1,1.631587,No,No,-0.567911,1.159878,1.314595,1.159492,0.191588,-1.767107,0.190832,...,False,False,False,False,False,False,True,False,False,True
2,-0.761738,No,No,-0.567911,0.787697,0.710014,0.788074,0.312997,0.644196,0.312592,...,False,False,False,False,True,False,False,False,True,False
3,1.455237,No,No,-0.567911,-0.145532,0.710014,-0.145374,1.123050,-1.566165,1.122762,...,False,False,False,False,False,False,True,False,False,False
4,0.019241,No,No,-0.567911,0.693263,0.911541,0.693313,0.627465,1.397728,0.626357,...,False,False,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,-1.618297,No,No,0.622715,-0.571410,0.558869,-0.571253,-1.360848,0.644196,-1.361603,...,False,False,False,False,False,False,False,False,True,False
4246,-1.920612,No,No,1.292443,-0.284405,0.508488,-0.284792,0.181637,0.242312,0.181466,...,False,False,False,False,False,False,False,False,False,True
4247,-0.081530,No,No,1.813342,0.058149,-0.297619,0.058307,1.371838,0.995845,1.370964,...,False,False,False,False,True,False,False,False,True,False
4248,-0.484616,No,No,2.855140,-0.221449,1.213831,-0.221618,1.407664,0.141841,1.408428,...,False,False,False,False,True,False,False,False,False,False
4249,0.825414,No,No,2.334241,1.104329,0.357342,1.103943,1.067322,-1.164281,1.066565,...,False,False,False,False,False,True,False,False,False,False

In [18]:
df.isna().sum()

account_length             0
international_plan         0
voice_mail_plan            0
number_vmail_messages      0
total_day_minutes          0
                          ..
tenure_group_100-150       0
tenure_group_150-200       0
tenure_group_200+          0
area_code_area_code_415    0
area_code_area_code_510    0
Length: 76, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [21]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [22]:
X.isna().sum()

account_length                0
international_plan         4250
voice_mail_plan            4250
number_vmail_messages         0
total_day_minutes             0
                           ...
tenure_group_100-150          0
tenure_group_150-200          0
tenure_group_200+             0
area_code_area_code_415       0
area_code_area_code_510       0
Length: 75, dtype: int64

In [23]:
X = X.fillna(X.mean())

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [29]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [30]:
X = X.apply(pd.to_numeric, errors='coerce')

In [31]:
X.isna().sum()

account_length                0
international_plan         4250
voice_mail_plan            4250
number_vmail_messages         0
total_day_minutes             0
                           ...
tenure_group_100-150          0
tenure_group_150-200          0
tenure_group_200+             0
area_code_area_code_415       0
area_code_area_code_510       0
Length: 76, dtype: int64

In [32]:
X = X.fillna(X.mean())

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [35]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [36]:
X = X.apply(pd.to_numeric, errors='coerce')

In [37]:
import numpy as np

X = X.replace([np.inf, -np.inf], np.nan)

In [38]:
X = X.fillna(0)

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

In [40]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [41]:
import numpy as np

print(np.isnan(X_train).sum())
print(np.isnan(X_test).sum())

0
0

In [42]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [43]:
df['Churn'].unique()

array([-0.40465528,  2.47123925])

In [44]:
df['Churn'] = df['Churn'].apply(lambda x: 1 if x > 0 else 0)

In [45]:
df['Churn'].unique()

array([0, 1])

In [46]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

In [48]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [49]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [50]:
print(df['Churn'].unique())
print(df['Churn'].dtype)

[0 1]
int64

In [51]:
df['Churn'] = (df['Churn'] > 0).astype(int)

In [52]:
df['Churn'].unique()

array([0, 1])

In [53]:
X = df.drop('Churn', axis=1)
y = df['Churn']

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [55]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
C:\Users\ashuy\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [56]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [58]:
df = df.apply(pd.to_numeric, errors='coerce')

In [59]:

df.dtypes

account_length             float64
international_plan         float64
voice_mail_plan            float64
number_vmail_messages      float64
total_day_minutes          float64
                            ...
tenure_group_100-150          bool
tenure_group_150-200          bool
tenure_group_200+             bool
area_code_area_code_415       bool
area_code_area_code_510       bool
Length: 76, dtype: object

In [60]:
df = df.fillna(df.mean())

In [62]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values